=== wesolowski/temp-data-provider/dataprovider.schema.xsd
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="xervice:dataprovider-01" elementFormDefault="qualified">
    <!--
     XML Schema for the Xervice data provider schemes
    -->
    <xsd:element name="DataProviders">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="DataProvider" minOccurs="0" maxOccurs="unbounded">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="DataElement" minOccurs="0" maxOccurs="unbounded">
                                <xsd:complexType>
                                    <xsd:attribute name="name" type="xsd:string" use="required"></xsd:attribute>
                                    <xsd:attribute name="type" type="xsd:string" use="required"></xsd:attribute>
                                    <xsd:attribute name="default" type="xsd:string" use="optional" default=""></xsd:attribute>
                                    <xsd:attribute name="singleton" type="xsd:string" use="optional"></xsd:attribute>
                                    <xsd:attribute name="allownull" type="xsd:boolean" use="optional" default="false"></xsd:attribute>
                                </xsd:complexType>
                            </xsd:element>
                        </xsd:sequence>
                        <xsd:attribute name="name" type="xsd:string" use="required"></xsd:attribute>
                        <xsd:attribute name="ConvertUnderlines" type="xsd:boolean" use="optional" default="false"></xsd:attribute>
                        <xsd:attribute name="deprecated" type="xsd:boolean" use="optional"></xsd:attribute>
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

</xsd:schema>

=== wesolowski/temp-data-provider/tests/Xervice/DataProvider/Schema/default.testprovider.xml
<?xml version="1.0"?>

<DataProviders
  xmlns="xervice:dataprovider-01"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="xervice:dataprovider-01 http://static.xervice.online/schema/dataprovider.schema.xsd"
>

    <DataProvider name="Default">
        <DataElement name="String" default="Text" type="string"/>
        <DataElement name="EmptyText" default="''" type="string"/>
        <DataElement name="Number" default="5" type="int"/>
        <DataElement name="Boolean" default="true" type="bool"/>
        <DataElement name="Float" default="1.5" type="float"/>
        <DataElement name="Double" default="2.5" type="double"/>
        <DataElement name="List" default="[]" type="array"/>
        <DataElement name="Object" type="object"/>
    </DataProvider>

</DataProviders>

=== wesolowski/temp-data-provider/tests/Xervice/DataProvider/Schema/keyvalue.testprovider.xml
<?xml version="1.0"?>

<DataProviders
  xmlns="xervice:dataprovider-01"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="xervice:dataprovider-01 http://static.xervice.online/schema/dataprovider.schema.xsd"
>

    <DataProvider name="TestKeyValue">
        <DataElement name="Key" type="string"/>
        <DataElement name="value" type="string" allownull="true"/>
        <DataElement name="default" type="string" default="Test"/>
        <DataElement name="IsActive" type="bool" default="false"/>
    </DataProvider>

    <DataProvider name="TestKeyValueCollection">
        <DataElement name="keyValues" singleton="OneValue" type="TestKeyValue[]"/>
        <DataElement name="ChildValue" singleton="ChildValue" allownull="true" type="TestKeyValue"/>
    </DataProvider>
</DataProviders>
